language: go

go:
  - 1.14

services:
  - docker

before_deploy:
  - sh ./devops/build_push_registry.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./devops/deploy.sh

notifications:
  email:
    on_failure: bobgel12@gmail.com
