language: go

go:
  - latest

services:
  - docker

before_deploy:
  - sh ./devops/build_push_registry.sh

deploy:
  - sh ./devops/deploy.sh

notifications:
  email:
    on_failure: bobgel12@gmail.com
