apiVersion: v1
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: es-backend                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: es-backend
spec:
  type: NodePort                              # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: es-backend               # Selects any Pod with labels `app=es-backend`
  ports:
  - name: http
    port: 8080
    targetPort: 8080
