apiVersion: apps/v1
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: es-backend                                # Name of the Kubernetes resource
  labels:
    app: es-backend
spec:                                             # Spec for the container which will run in the Pod
  replicas: 2                                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: es-backend                             # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: es-backend
    spec:
      imagePullSecrets:
      - name: es-dev-us-icr-io
      containers:
      - name: es-backend
        image: us.icr.io/esregistry/esbackend:%IMAGE_VERSION%       # The image we are getting from ibmcloud registry
        imagePullPolicy: IfNotPresent             # If we have not pulled it before, get it from ibmcloud registry
        ports:
          - name: http
            containerPort: 80                     # Should match the port number that the Go application listens on
